repo: openworm/OpenWorm
shortDescription: "Project Home repo for OpenWorm Wiki and Project-wide issues"
contributor-guide: "http://docs.openworm.org/en/latest/community/#contribution-best-practices"
coordinator: stephen@openworm.org
documentation: "http://docs.openworm.org/en/latest/"
gitter: "http://gitter.im/openworm/OpenWorm"
